// Starter text for the info pages. Override any page by adding a row with the same slug to the `pages` table.
const E = "support@octovvpn.com";

export const PAGES: Record<string, { title: string; body: string }> = {
  privacy: {
    title: "Privacy Policy",
    body: `Octo Tech Ltd operates OctoVVPN with an uncompromising commitment to user privacy and digital freedom.\n\nStrict Zero-Logs Policy: We do not log, monitor, record, or store your browsing activity, destination IP addresses, DNS queries, connection timestamps, or session bandwidth history. When you connect through OctoVVPN, your internet traffic is encrypted with AES-256-GCM cipher and routed through isolated nodes without permanent trace.\n\nAccount Information: We only retain your registered email address and current subscription status to manage authentication, plan entitlements, and active device sessions.\n\nPayment Security: All financial transactions are securely processed by our certified payment partners (including Stripe). OctoVVPN never receives or stores your full credit card numbers or sensitive payment credentials.\n\nTelemetry & Operational Data: Minimal, non-identifiable telemetry (such as aggregate network server load) is processed transiently in RAM solely to balance gateway performance and mitigate network abuse.\n\nData Ownership: We never sell, rent, monetize, or share your personal data with third-party advertisers or data brokers.\n\nPrivacy Inquiries: For questions regarding our privacy practices or data handling, reach our team directly at ${E}.`,
  },
  terms: {
    title: "Terms of Service",
    body: `Welcome to OctoVVPN. By accessing or using our applications and network services, you agree to comply with and be bound by these Terms of Service.\n\nPermitted Use: OctoVVPN is provided to protect your online privacy, secure network communications, and enable unrestricted digital access. You agree to use the service in compliance with applicable laws and regulations. You must not use our infrastructure for malicious activities including fraud, distributed denial-of-service (DDoS) attacks, automated spamming, network intrusion, or distributing harmful material.\n\nService Availability & Performance: While we maintain a 99.9% network uptime goal and deploy advanced obfuscation transports (Shadowsocks, Obfs4) to bypass restrictive firewalls, network speeds and censorship resistance may vary depending on local ISP restrictions and geopolitical filtering policies.\n\nAccount Responsibility: You are responsible for safeguarding your account credentials. Sharing access beyond your plan's simultaneous device limit may result in session throttling or temporary suspension.\n\nModifications & Updates: We reserve the right to update service plans, features, or these terms with advance notice posted on our website.\n\nSupport & Inquiries: For questions regarding service terms or usage policies, contact us at ${E}.`,
  },
  refunds: {
    title: "Refund Policy",
    body: `We want you to experience OctoVVPN with total confidence. All paid subscriptions include an unconditional 30-Day Money-Back Guarantee.\n\n30-Day Guarantee: If you are not completely satisfied with our service speed, security, or network availability for any reason, you are entitled to a 100% full refund within 30 days of your initial purchase.\n\nHow to Request a Refund: Simply send an email to ${E} from the email address associated with your OctoVVPN account. Include your order ID or transaction reference. No complicated interrogation or hurdles required.\n\nProcessing Timeline: Once received, refund requests are reviewed and initiated within 24 to 48 business hours. Funds will be credited directly back to your original payment method (Stripe, card, or processor timeline typically 3–7 business days).\n\nFree Tier: The free Stealth plan does not incur any charges and carries no financial obligations.`,
  },
  cookies: {
    title: "Cookie Policy",
    body: `OctoVVPN respects your privacy both in our apps and on our website.\n\nEssential Cookies Only: We exclusively utilize strictly necessary, privacy-safe session cookies required for core site functionality, including authentication states and dark/light UI preferences.\n\nNo Cross-Site Tracking: We do not deploy third-party advertising cookies, behavioral fingerprinting scripts, or cross-site tracking pixels.\n\nCookie Control: You can inspect, disable, or delete cookies at any time through your browser settings. Disabling essential cookies may affect your ability to stay logged in to account areas.`,
  },
  gdpr: {
    title: "GDPR Compliance & Data Rights",
    body: `Octo Tech Ltd complies with the European Union General Data Protection Regulation (GDPR) and the UK Data Protection Act.\n\nYour Statutory Rights: As a user, you possess fundamental rights regarding your personal data:\n• Right of Access: You can request confirmation and a copy of the minimal data we hold about you.\n• Right to Rectification: You may update or correct inaccurate account details.\n• Right to Erasure ("Right to be Forgotten"): You can request the permanent deletion of your account and all associated records.\n• Right to Data Portability: You may request your account information in a machine-readable format.\n• Right to Object & Restrict Processing: You may object to any non-essential data processing at any time.\n\nExercising Your Rights: To submit a GDPR data access or deletion request, email our Data Protection team at ${E} from your registered account address.\n\nAccount Erasure: For instant account deletion instructions, visit our Delete Account page.`,
  },
  about: {
    title: "About OctoVVPN",
    body: `OctoVVPN was founded by Octo Tech Ltd with a clear mission: to ensure open, private, and uncensored internet access for everyone worldwide.\n\nEngineered for Adverse Networks: Traditional VPN protocols are routinely detected, throttled, and blocked by modern deep packet inspection (DPI) firewalls. OctoVVPN integrates cutting-edge cryptographic obfuscation transports—including Shadowsocks and Obfs4—making your encrypted traffic indistinguishable from everyday HTTPS web traffic.\n\nMilitary-Grade Cryptography: All tunnels employ authenticated AES-256-GCM encryption with autonomous multi-hop routing, protecting your personal data, VoIP calls, and browsing from surveillance and cyber threats.\n\nZero Compromises: Built from the ground up without corporate trackers, third-party ad networks, or data brokers. Our multi-platform client applications for Windows and Android offer seamless one-tap protection.\n\nGet in Touch: For partnership opportunities, press inquiries, or general questions, contact us at ${E}.`,
  },
  contact: {
    title: "Contact Support",
    body: `Need assistance with your account, connection setup, or subscription? Our dedicated support team is available 24/7.\n\nPrimary Support Email: ${E}\n\nBilling & Payments: Have questions about invoicing, subscriptions, or receipt generation? Reach out directly to ${E}.\n\nTechnical Assistance: Experiencing connection issues or configuring stealth protocols in restrictive environments? Include your operating system (Windows or Android) and target server location for rapid troubleshooting.\n\nResponse Guarantee: We respond to all inquiries within 12 to 24 hours. Enterprise and priority inquiries receive expedited handling.\n\nAffiliate & Business Partnerships: Interested in our affiliate program? Check out our Affiliates page or email our partnership desk at ${E}.`,
  },
  status: {
    title: "Server Live Status",
    body: `Real-time health telemetry across the global OctoVVPN gateway network. Each server node is continuously monitored for latency, bandwidth availability, and obfuscation health.\n\nAutomatic Failover: If a node experiences ISP throttling or network disruption, our autonomous routing system automatically reroutes client connections to the nearest healthy alternative without dropping your session.\n\nIncident Reporting: Notice connectivity degradation in a specific region? Contact our network operations team at ${E}.`,
  },
  "delete-account": {
    title: "Delete Your Account",
    body: `We honor your digital sovereignty and right to be forgotten. You can request the complete and irreversible erasure of your OctoVVPN account and all associated records at any time.\n\nHow to Submit a Deletion Request:\n1. Send an email to ${E} using the registered email address tied to your OctoVVPN account.\n2. Set the subject line to: "Delete Account Request".\n3. Include a brief statement confirming your request to terminate the account.\n\nWhat Gets Erased:\n• Your account email, hashed password, and authentication tokens.\n• All active device sessions and client profile bindings.\n• Saved billing references and plan subscriptions (active recurring charges will be cancelled immediately).\n\nTimeline: Account deletion requests are confirmed and queued immediately, with full system purging completed within 48 hours. A final confirmation email will be sent once the process is complete.`,
  },
};
